name: 'Steam - Deploy'
author: Webber Takken <webber@takken.io>
description: 'Deploy game builds to Steam using the SteamSDK.'
inputs:
  steamUsername:
    required: true
    default: ''
    description: 'The username of your builder account.'
  steamPassword:
    required: true
    default: ''
    description: 'The password of your builder account.'
  steamMfa:
    required: false
    default: ''
    description: 'The 5 character MFA code emailed when logging in.'
outputs: {}
branding:
  icon: 'package'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'action/Dockerfile'
